{% set name = "pylance" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lancedb/lance/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6f07811c7ff66f754a785555d0639cdc859869d22162ffb4ab5784cfd8ac7c00

build:
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - libprotobuf
  host:
    - python
    - pip
    - maturin
  run:
    - python
    - numpy >=1.22
    - pyarrow >=12

test:
  imports:
    - lance
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lancedb/lance
  summary: python wrapper for Lance columnar format
  license: Apache-2.0
  license_file:
    - LICENSE
    - python/LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - yhori991
