{% set name = "pylance" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lancedb/lance/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c43f81c3e78379101776f9038e0a1455a03464d9e00fb6dc94a798ae507b8250

build:
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - libprotobuf
  host:
    - python
    - pip
    - maturin
  run:
    - python
    - numpy >=1.22
    - pyarrow >=12

test:
  imports:
    - lance
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lancedb/lance
  summary: python wrapper for Lance columnar format
  license: Apache-2.0
  license_file:
    - LICENSE
    - python/LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - yhori991
