{% set name = "pylance" %}
{% set version = "0.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lancedb/lance/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0a57cd9dc4683de0c9612f5b2ea49fd8dc334ad15cafa091e5af4d403b448659

build:
  number: 0
  skip: true  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin <1.8.0                         # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - libprotobuf
  host:
    - python
    - pip
    - maturin <1.8.0
    - openssl
  run:
    - python
    - numpy >=1.22
    - pyarrow >=14

test:
  imports:
    - lance
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lancedb/lance
  summary: python wrapper for Lance columnar format
  license: Apache-2.0
  license_file:
    - LICENSE
    - python/LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - yhori991
