{% set name = "pylance" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lancedb/lance/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fc1aee14aecfc3b22b3f708378855b75eb4d0201e7dfbb6fe01a02a7965cbc83

build:
  number: 0
  skip: true  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin                                # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - libprotobuf
  host:
    - python
    - pip
    - maturin
  run:
    - python
    - numpy >=1.22
    - pyarrow >=12,<15.0.1

test:
  imports:
    - lance
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lancedb/lance
  summary: python wrapper for Lance columnar format
  license: Apache-2.0
  license_file:
    - LICENSE
    - python/LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - yhori991
