context:
  version: "0.31.0"
  python_min: "3.9"
  build_number: 1

package:
  name: pylance
  version: ${{ version }}

source:
  url: https://github.com/lancedb/lance/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 9d77f37ae2dce1ef8efae996aa35272a95d89531994378d5d143999b20b301f5

build:
  number: ${{ build_number }}
  script:
    - if: unix
      then:
        - export OPENSSL_DIR=${{ PREFIX }}
    - if: win
      then:
        - set OPENSSL_DIR=${{ PREFIX }}
        - set PYTHONIOENCODING=utf-8
    - cd python
    - cargo-bundle-licenses --format yaml --output ../THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv


requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - libprotobuf
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin >=1.3.2,<2
  host:
    - python
    - pip
    - maturin >=1.3.2,<2
    - openssl
  run:
    - python
    - numpy >=1.22
    - pyarrow >=14

tests:
  - python:
      imports:
        - lance
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: python wrapper for Lance columnar format
  license: Apache-2.0
  license_file:
    - LICENSE
    - python/LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/lancedb/lance

extra:
  recipe-maintainers:
    - yhori991
