azure:
  free_disk_space: true
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
# See https://github.com/conda-forge/rust-activation-feedstock/issues/58
conda_build:
  error_overlinking: false
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
